### ISSUE TITLE
add-file with a relative path is crashing

### ISSUE THREAD

**Issue by mrlowe** [awatson1978/leaderboard-tinytests#3]
I'm trying to get tinytest inside a package to work, but can't follow the example in the cookbook. Specifically, the line

api.add_files('../../leaderboard.js', 'client');

Produces the following exception and stack trace. This may have something to do with meteor 1.2 (https://github.com/meteor/meteor/issues/5252). I'm using meteor 1.2.1 on OS X.

```
$ meteor test-packages leaderboard-tinytests
[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> Started MongoDB.                           

/Users/matt/.meteor/packages/meteor-tool/.1.1.10.1fb765q++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: Path contains forbidden segment '..'
    at Builder._sanitize (/tools/isobuild/builder.js:143:15)
    at Builder.generateFilename (/tools/isobuild/builder.js:340:20)
    at Builder.writeToGeneratedFilename (/tools/isobuild/builder.js:352:28)
    at /tools/isobuild/isopack.js:1346:27
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/matt/.meteor/packages/meteor-tool/.1.1.10.1fb765q++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at _.each._.each.builder.generateFilename.directory (/tools/isobuild/isopack.js:1320:11)
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/matt/.meteor/packages/meteor-tool/.1.1.10.1fb765q++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/isopack.js:1233:9
    at [object Object]._.extend.saveToPath (/tools/isobuild/isopack.js:1585:26)
    at /tools/isobuild/isopack-cache.js:289:23
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at [object Object]._.extend._loadLocalPackage (/tools/isobuild/isopack-cache.js:227:18)
    at /tools/isobuild/isopack-cache.js:166:14
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at [object Object]._.extend._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:158:20)
    at /tools/isobuild/isopack-cache.js:73:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/Users/matt/.meteor/packages/meteor-tool/.1.1.10.1fb765q++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object]._.extend.eachPackage (/tools/packaging/package-map.js:49:7)
    at [object Object]._.extend.buildLocalPackages (/tools/isobuild/isopack-cache.js:72:24)
    at /tools/project-context.js:735:25
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at ProjectContext._.extend._buildLocalPackages (/tools/project-context.js:734:18)
    at /tools/project-context.js:257:35
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:247:18)
    at ProjectContext._.extend.saveChangedMetadata (/tools/project-context.js:235:10)
    at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:240:10)
    at /tools/runners/run-app.js:517:29
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at bundleApp (/tools/runners/run-app.js:516:31)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:594:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:858:28)
    at /tools/runners/run-app.js:396:12
```

**Comment by cubitworx** [comment]
I have created a repository reproducing this problem in its simplest form...
https://github.com/cubitworx/meteor-1.2-forbidden-path-segment

**Comment by ToraSonic** [comment]
same problem here
